export const FONT_OPTIONS: string[] = [
  "Inter, sans-serif",
  "DM Sans, sans-serif",
  "Rubik, sans-serif",
  "Nunito, sans-serif",
  "Poppins, sans-serif",
  "Montserrat, sans-serif",
  "Work Sans, sans-serif",
  "Figtree, sans-serif",
  "Raleway, sans-serif",
  "Noto Sans, sans-serif",
  "Merriweather, serif",
  "JetBrains Mono, monospace",
  "Plus Jakarta Sans, sans-serif",
  "Sora, sans-serif",
  "Manrope, sans-serif",
  "Space Grotesk, sans-serif",
  "Cabin, sans-serif",
  "Exo 2, sans-serif",
  "Karla, sans-serif",
  "Source Sans 3, sans-serif",
  "Urbanist, sans-serif",
  "Merriweather Sans, sans-serif",
  "DM Mono, monospace",
  "Fira Code, monospace",
  "Playfair Display, serif",
  "Cinzel, serif",
  "Cormorant Garamond, serif",
  "Lobster, cursive",
  "Pacifico, cursive",
  "Caveat, cursive",
  "Shadows Into Light, cursive",
  "Great Vibes, cursive",
  "Dancing Script, cursive",
  "Gloria Hallelujah, cursive",
  "Permanent Marker, cursive",
  "Rock Salt, cursive",
  "Bangers, cursive",
  "Fredericka the Great, cursive",
  "UnifrakturCook, cursive",
  "MedievalSharp, cursive",
  "New Rocker, cursive",
  "Pirata One, cursive",
  "Metal Mania, cursive",
  "Rubik Glitch, cursive",
  "Press Start 2P, cursive",
  "Creepster, cursive",
  "Monoton, cursive",
  "Black Ops One, sans-serif",
  "Almendra SC, serif",
  "IM Fell English SC, serif",
  "Berkshire Swash, cursive",
  "Rye, cursive",
  "Tilt Prism, cursive",
  "Orbitron, sans-serif",
  "Cinzel Decorative, serif",
  "Special Elite, cursive",
  "Indie Flower, cursive",
  "Courgette, cursive",
  "Poiret One, cursive",
  "Amatic SC, cursive",
  "Great Vibes, cursive",
  "Tangerine, cursive"
];
