export const FONT_OPTIONS: string[] = [
  "Inter, sans-serif",
  "DM Sans, sans-serif",
  "Rubik, sans-serif",
  "Nunito, sans-serif",
  "Poppins, sans-serif",
  "Montserrat, sans-serif",
  "Work Sans, sans-serif",
  "Figtree, sans-serif",
  "Raleway, sans-serif",
  "Noto Sans, sans-serif",
  "Merriweather, serif",
  "JetBrains Mono, monospace",
  "Arial, sans-serif",
  "Georgia, serif",
  "Courier New, monospace",
  "Comic Sans MS, cursive",
  "Trebuchet MS, sans-serif",
  "Times New Roman, serif",
  "Verdana, sans-serif"
];
